//! codefacts CLI: one self-driving binary. `start` boots the iii engine (with
//! every provider auto-configured) and runs the worker in-process — no setup.
//! The user only edits settings (repo, senders). Business logic is in core.

mod store;
mod worker;

use std::io::{BufRead, Write};
use std::net::TcpStream;
use std::path::PathBuf;
use std::process::{Command, Stdio};
use std::time::{Duration, Instant};

use anyhow::{Context, Result};
use clap::{Parser, Subcommand};
use codefacts_core::config::{Config, EngineConfig, RepoConfig, Schedule, Storage};
use codefacts_core::paths;
use codefacts_core::secrets::Secrets;

/// Engine WebSocket port (iii default).
const ENGINE_PORT: u16 = 49134;

#[derive(Parser)]
#[command(name = "codefacts", version, about = "Codebase-knowledge engine → Telegram")]
struct Cli {
    #[command(subcommand)]
    cmd: Cmd,
}

#[derive(Subcommand)]
enum Cmd {
    /// Set repo, interest, times, and Telegram credentials (interactive).
    Init,
    /// Start everything in the background (engine + providers + worker).
    Start,
    /// Stop the background engine + worker.
    Stop,
    /// Show status.
    Status,
    /// Run one mining pass now.
    Mine,
    /// Select + push one insight now.
    Emit,
    /// Open the iii observability console (127.0.0.1:3113).
    Console,
    /// Print the knowledge graph nodes for the first repo.
    Graph,
    /// Print recent emissions (facts already sent).
    History,
    /// Stop, remove login item, and optionally purge config/data.
    Uninstall,
    /// Internal: run the worker in-process (spawned by `start`).
    #[command(name = "__worker", hide = true)]
    Worker,
}

fn main() -> Result<()> {
    match Cli::parse().cmd {
        Cmd::Init => init(),
        Cmd::Start => start(),
        Cmd::Stop => stop(),
        Cmd::Status => status(),
        Cmd::Mine => trigger_fn("codefacts::mine"),
        Cmd::Emit => trigger_fn("codefacts::emit"),
        Cmd::Console => console(),
        Cmd::Graph => graph(),
        Cmd::History => history(),
        Cmd::Uninstall => uninstall(),
        Cmd::Worker => tokio::runtime::Runtime::new()?.block_on(worker::run()),
    }
}

// ── init ────────────────────────────────────────────────────────────────

fn init() -> Result<()> {
    check_prereqs();

    eprintln!("codefacts setup — answers are saved locally.\n");
    let token = prompt("Telegram bot token (from @BotFather)")?;
    let chat_id = prompt("Telegram chat id (numeric)")?;
    let repo = prompt_default("Repo path to learn", &cwd_string())?;
    let interest = prompt_default(
        "What do you care about? (free text)",
        "the libraries we use and how the API and services fit together",
    )?;
    let times = prompt_default("Daily times (comma HH:MM)", "10:00,14:00,20:00")?;

    let config = Config {
        schedule: Schedule {
            times: times.split(',').map(|s| s.trim().to_string()).collect(),
            timezone: "Europe/Oslo".into(),
        },
        repos: vec![RepoConfig {
            path: repo,
            interest,
            storage: Storage::Central,
        }],
        engine: EngineConfig::default(),
        enabled: true,
        history_keep: 200,
    };
    config.validate()?;
    let cfg_path = paths::config_path()?;
    config.save(&cfg_path)?;

    let secrets = Secrets {
        telegram_bot_token: token,
        telegram_chat_id: chat_id,
    };
    let sec_path = paths::secrets_path()?;
    secrets.save(&sec_path)?;

    eprintln!("\n✓ config: {}", cfg_path.display());
    eprintln!("✓ secrets (0600): {}", sec_path.display());
    eprintln!("\nNext: `codefacts start`.");
    Ok(())
}

// ── lifecycle ─────────────────────────────────────────────────────────────

fn run_dir() -> Result<PathBuf> {
    let d = paths::central_data_dir()?.join("run");
    std::fs::create_dir_all(&d)?;
    Ok(d)
}

/// The engine's private working dir (config.yaml + state store live here).
fn engine_dir() -> Result<PathBuf> {
    let d = paths::central_data_dir()?.join("engine");
    std::fs::create_dir_all(d.join("config"))?;
    std::fs::create_dir_all(d.join("data"))?;
    Ok(d)
}

/// Write the engine config listing every provider, so `iii --config` boots them
/// all itself — no `iii worker add` and nothing for the user to do.
fn ensure_engine_config() -> Result<PathBuf> {
    let dir = engine_dir()?;
    let cfg = dir.join("config.yaml");
    let data = dir.join("data");
    let confdir = dir.join("config");
    let yaml = format!(
        "# Auto-generated by `codefacts start`. Do not edit.\nworkers:\n\
         \x20 - name: iii-observability\n\
         \x20   config: {{ enabled: true, service_name: codefacts, exporter: memory, \
         metrics_enabled: true, metrics_exporter: memory, logs_enabled: true, \
         logs_exporter: memory, logs_console_output: false, sampling_ratio: 1.0 }}\n\
         \x20 - name: queue\n\
         \x20   config: {{ adapter: {{ name: builtin }} }}\n\
         \x20 - name: state\n\
         \x20   config: {{ adapter: {{ name: kv, config: {{ store_method: file_based, file_path: {data}/state_store.db }} }} }}\n\
         \x20 - name: cron\n\
         \x20   config: {{ adapter: {{ name: local }} }}\n\
         \x20 - name: configuration\n\
         \x20   config: {{ adapter: {{ name: fs, config: {{ directory: {confdir} }} }}, ttl_seconds: 0 }}\n\
         \x20 - name: http\n\
         \x20   config: {{ host: 127.0.0.1, port: 3111, default_timeout: 30000 }}\n",
        data = data.display(),
        confdir = confdir.display(),
    );
    std::fs::write(&cfg, yaml)?;
    Ok(cfg)
}

fn start() -> Result<()> {
    check_prereqs();
    if Config::load(paths::config_path()?).is_err() {
        anyhow::bail!("no config yet — run `codefacts init` first");
    }
    let run = run_dir()?;
    let logs = paths::central_data_dir()?.join("logs");
    std::fs::create_dir_all(&logs)?;
    let edir = engine_dir()?;
    let cfg = ensure_engine_config()?;

    // Engine: boots every provider from the generated config.
    let engine_pid = spawn_bg(
        "iii",
        &["--config".into(), cfg.to_string_lossy().into()],
        &logs.join("engine.log"),
        Some(&edir),
    )?;
    std::fs::write(run.join("engine.pid"), engine_pid.to_string())?;

    if !wait_for_port(ENGINE_PORT, 45) {
        eprintln!("warning: engine not reachable on :{ENGINE_PORT} yet; worker will keep retrying");
    }

    // Worker: this same binary, in-process, via the hidden `__worker` command.
    let exe = std::env::current_exe()?;
    let worker_pid = spawn_bg(
        &exe.to_string_lossy(),
        &["__worker".into()],
        &logs.join("worker.log"),
        None,
    )?;
    std::fs::write(run.join("worker.pid"), worker_pid.to_string())?;

    register_login_item()?;
    eprintln!("✓ codefacts running (engine pid {engine_pid}, worker pid {worker_pid})");
    eprintln!("  console: codefacts console   logs: {}", logs.display());
    Ok(())
}

/// Poll until the engine's WebSocket port accepts connections (or timeout).
fn wait_for_port(port: u16, secs: u64) -> bool {
    let deadline = Instant::now() + Duration::from_secs(secs);
    while Instant::now() < deadline {
        if TcpStream::connect(("127.0.0.1", port)).is_ok() {
            return true;
        }
        std::thread::sleep(Duration::from_millis(300));
    }
    false
}

fn stop() -> Result<()> {
    let run = run_dir()?;
    for name in ["worker.pid", "engine.pid"] {
        let p = run.join(name);
        if let Ok(pid) = std::fs::read_to_string(&p) {
            kill(pid.trim());
            let _ = std::fs::remove_file(&p);
        }
    }
    eprintln!("✓ stopped");
    Ok(())
}

fn status() -> Result<()> {
    let run = run_dir()?;
    for name in ["engine.pid", "worker.pid"] {
        match std::fs::read_to_string(run.join(name)) {
            Ok(pid) => println!("{name}: {}", pid.trim()),
            Err(_) => println!("{name}: not running"),
        }
    }
    // Live status from the worker (best effort).
    let _ = Command::new("iii")
        .args(["trigger", "codefacts::status", "--json", "{}"])
        .status();
    Ok(())
}

// ── actions via iii ─────────────────────────────────────────────────────

fn trigger_fn(func: &str) -> Result<()> {
    // Generous timeout: a mining pass runs claude, which can take a minute+.
    let status = Command::new("iii")
        .args(["trigger", func, "--json", "{}", "--timeout-ms", "300000"])
        .status()
        .with_context(|| format!("running `iii trigger {func}` — is the engine up?"))?;
    if !status.success() {
        anyhow::bail!("iii trigger {func} failed");
    }
    Ok(())
}

fn console() -> Result<()> {
    eprintln!("Opening iii console at http://127.0.0.1:3113 …");
    Command::new("iii").arg("console").status()?;
    Ok(())
}

fn graph() -> Result<()> {
    let repo = first_repo()?;
    let scope = format!("cf:{}:nodes", paths::repo_id(&repo.path));
    let payload = serde_json::json!({ "scope": scope }).to_string();
    trigger_with_payload("state::list", &payload)
}

fn history() -> Result<()> {
    let repo = first_repo()?;
    let scope = format!("cf:{}:emissions", paths::repo_id(&repo.path));
    let payload = serde_json::json!({ "scope": scope }).to_string();
    trigger_with_payload("state::list", &payload)
}

fn trigger_with_payload(func: &str, payload: &str) -> Result<()> {
    let status = Command::new("iii").args(["trigger", func, "--json", payload]).status()?;
    if !status.success() {
        anyhow::bail!("iii trigger {func} failed (is the engine up?)");
    }
    Ok(())
}

fn uninstall() -> Result<()> {
    let _ = stop();
    if let Ok(al) = login_item() {
        let _ = al.disable();
    }
    if confirm("Purge config + knowledge data?")? {
        if let Ok(p) = paths::config_path() {
            if let Some(dir) = p.parent() {
                let _ = std::fs::remove_dir_all(dir);
            }
        }
        let _ = std::fs::remove_dir_all(paths::central_data_dir()?);
        eprintln!("✓ purged config + data");
    }
    eprintln!("✓ uninstalled. Remove the binary via your package manager (brew/npm/cargo).");
    Ok(())
}

// ── helpers ───────────────────────────────────────────────────────────────

fn first_repo() -> Result<RepoConfig> {
    let cfg = Config::load(paths::config_path()?).context("run `codefacts init` first")?;
    cfg.repos
        .into_iter()
        .next()
        .ok_or_else(|| anyhow::anyhow!("no repos configured"))
}

fn check_prereqs() {
    for (bin, hint) in [
        ("iii", "install from https://iii.dev"),
        ("claude", "install Claude Code and run `claude login`"),
    ] {
        if which(bin).is_none() {
            eprintln!("warning: `{bin}` not found on PATH — {hint}");
        }
    }
}

fn which(bin: &str) -> Option<PathBuf> {
    let status = Command::new("sh")
        .arg("-c")
        .arg(format!("command -v {bin}"))
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
        .ok()?;
    status.success().then(|| PathBuf::from(bin))
}

fn cwd_string() -> String {
    std::env::current_dir()
        .map(|p| p.to_string_lossy().to_string())
        .unwrap_or_default()
}

fn prompt(label: &str) -> Result<String> {
    eprint!("{label}: ");
    std::io::stderr().flush()?;
    let mut line = String::new();
    std::io::stdin().lock().read_line(&mut line)?;
    Ok(line.trim().to_string())
}

fn prompt_default(label: &str, default: &str) -> Result<String> {
    let v = prompt(&format!("{label} [{default}]"))?;
    Ok(if v.is_empty() { default.to_string() } else { v })
}

fn confirm(label: &str) -> Result<bool> {
    let v = prompt(&format!("{label} (y/N)"))?;
    Ok(matches!(v.to_lowercase().as_str(), "y" | "yes"))
}

// ── process management (best-effort, cross-platform) ──────────────────────

fn spawn_bg(bin: &str, args: &[String], log: &std::path::Path, cwd: Option<&PathBuf>) -> Result<u32> {
    let out = std::fs::File::create(log)?;
    let err = out.try_clone()?;
    let mut cmd = Command::new(bin);
    cmd.args(args).stdout(out).stderr(err).stdin(Stdio::null());
    if let Some(dir) = cwd {
        cmd.current_dir(dir);
    }
    detach(&mut cmd);
    let child = cmd
        .spawn()
        .with_context(|| format!("failed to spawn `{bin}`"))?;
    Ok(child.id())
}

#[cfg(unix)]
fn detach(cmd: &mut Command) {
    use std::os::unix::process::CommandExt;
    // New process group so it survives the CLI exiting.
    cmd.process_group(0);
}

#[cfg(not(unix))]
fn detach(_cmd: &mut Command) {}

#[cfg(unix)]
fn kill(pid: &str) {
    let _ = Command::new("kill").arg(pid).status();
}

#[cfg(not(unix))]
fn kill(pid: &str) {
    let _ = Command::new("taskkill").args(["/PID", pid, "/F"]).status();
}

// ── auto-launch ─────────────────────────────────────────────────────────

fn login_item() -> Result<auto_launch::AutoLaunch> {
    let exe = std::env::current_exe()?;
    Ok(auto_launch::AutoLaunchBuilder::new()
        .set_app_name("codefacts")
        .set_app_path(&exe.to_string_lossy())
        .set_args(&["start"])
        .build()?)
}

fn register_login_item() -> Result<()> {
    match login_item() {
        Ok(al) => {
            if let Err(e) = al.enable() {
                eprintln!("note: could not register login item: {e}");
            }
        }
        Err(e) => eprintln!("note: login item unavailable: {e}"),
    }
    Ok(())
}
